### ISSUE TITLE
Support Core Temperature

### ISSUE THREAD

**Issue by dbent** [Apokee/HotSpot#45]
Introduced in KSP 1.0.5. Parts may have a `ModuleCoreHeat`. Current core temperature is `ModuleCoreHeat.GetCoreTemperature()`. Maximum core temperature is `ModuleCoreHeat.CoreShutdownTemp`.

Need to deal with the fact that not every part may have a temperature value.

**Comment by pyalot** [comment]
I too would like to see a core-heat display trough HotSpot
