### ISSUE TITLE
Plotting

### ISSUE THREAD

**Issue by pyalot** [Apokee/HotSpot#48]
It'd be useful to have a tool that can record various (selectable) metrics for parts of interest and draw a time series of these values.

**Comment by dbent** [comment]
I think [Graphotron](http://www.kerbaltek.com/graphotron) is probably a more suitable mod for that kind of time series data. I'd like to keep Hot Spot focused on [heat map](https://en.wikipedia.org/wiki/Heat_map)-like graphical representations.
