### ISSUE TITLE
Temperature setting

### ISSUE THREAD

**Issue by pyalot** [Apokee/HotSpot#50]
HyperEdit supports setting the internal temperature of a part. Perhaps HotSpot could add that ability itself, as well as being able to set the core and skin temperature.

**Comment by dbent** [comment]
I'd consider that a 'cheat' feature and while that's perfectly fine for a single player game, I think it should be confined to a dedicated mod for such purposes, like HyperEdit.

**Comment by pyalot** [comment]
Sure it's a "cheat" feature. But when heat-testing stuff, using HyperEdit to set the heat is a pretty regular task. It's just cumbersome to click around in multiple mods dialogs to perform the tests you want.
