### ISSUE TITLE
Update toolbarwrapper

### ISSUE THREAD

**Issue by mheguy** [Apokee/HotSpot#75]
Ran into an issue between Hotspot and Contract Configurator due to a bug in the toolbar reflection wrapper. More info on how to resolve the issue here: http://forum.kerbalspaceprogram.com/index.php?/topic/55420-120-toolbar-1713-common-api-for-draggableresizable-buttons-toolbar/&page=55#comment-2770188

**Comment by dbent** [comment]
Thanks, will probably push a new release later today.

**Comment by dbent** [comment]
Relevant issue: blizzy78/ksp_toolbar#39
